version: '5.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development


  calendar:
    build:
      context: ./src/backend
      dockerfile: modules/calendar/Dockerfile
    ports:
      - "3002:3001"
    environment:
      - ENV=development
    depends_on:
      - postgres
  messaging:
    build:
      context: ./src/backend
      dockerfile: modules/messaging/Dockerfile
    ports:
      - "3003:3002"
    environment:
      - ENV=development
    depends_on:
      - postgres
  common:
    build:
      context: ./src/backend
      dockerfile: modules/common/Dockerfile
    ports:
      - "3005:3003"
    environment:
      - ENV=development
    depends_on:
      - postgres

  migrate:
    env_file:
      ./src/backend/.env
    build:
      context: ./src/backend
      dockerfile: database/Dockerfile
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      DB_NAME: ${DB_NAME:-mydb}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
    depends_on:
      - postgres
    command: up
    entrypoint: ["/app/migrate"]
  
volumes:
  postgres_data:
