version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    environment:
      - AIR_ENV=development
    stdin_open: true   
    tty: true  
    depends_on:
      - postgres       

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  migrate:
    image: migrate/migrate
    container_name: go-migrate
    volumes:
      - ./backend/app/migrate/migrations:/migrations
    depends_on:
    - postgres

volumes:
  postgres_data:
