FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY . .

RUN go mod tidy
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o generator .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/generator .

CMD ["./generator"]

