run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - tools
    - gen
    - third_party
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.gw\\.go$"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

linters-settings:
  govet:
    check-shadowing: false
  errcheck:
    check-type-assertions: false
    check-blank: false

