http.host: "0.0.0.0"
http.port: 9600
log.level: info

pipeline.workers: 1
pipeline.batch.size: 50
pipeline.batch.delay: 50

path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

dead_letter_queue.enable: false

monitoring.enabled: false
